### ISSUE TITLE
获取店主信息接口，shop _name 依旧不存在

### ISSUE THREAD

**Issue by nodejh** [fallfall/ScoringSystemServer#14]
![wechatimg1185](https://cloud.githubusercontent.com/assets/10287125/21292216/f9260e06-c537-11e6-9f4a-97f248320096.jpeg)

**Comment by fallfall** [comment]
因为这条数据的店名是空的（店名允许为空），接口可用，另外，shop_id已更改为shop_name ，迟关issue~
