### ISSUE TITLE
API 没有做权限控制

### ISSUE THREAD

**Issue by nodejh** [fallfall/ScoringSystemServer#17]
现在所有用户都能操作所有 API，比如添加／删除／修改管理员／DSR。

需要使用 token 来做身份认证。

用户登录成功（身份校验成功）后，后端返回一个 token。然后以后每次涉及权限相关的请求，前端都会把 token 发送给服务端，服务端根据 token 来校验用户是有有权限进行操作。

**Comment by fallfall** [comment]
已经返回token,记得每次请求带上这个参数就行，我那边还没有开验证~ 回来再调一下，现在可用了，师傅先调呗哈哈   Merry Christmas,
