### ISSUE TITLE
发送短信验证码code:100 是发送成功了？

### ISSUE THREAD

**Issue by nodejh** [fallfall/ScoringSystemServer#8]
```
[{"code":"100","state":"success","reason":"already send"}]
```

 1.{"code":"100","state":"success","reason":"already send"};
 2.{"code":"101","state":"fail","reason":"tel not register"};
 3.{"code":"102","state":"fail","reason":"send fail"};

code:100 是发送成功了？

**Comment by fallfall** [comment]
是的
